---
title: "MICE"
output: html_document
---

library("mice")
library("phylomice")
require(caper)

```{r setup, include=FALSE}

data <- read.csv("./Data/marsALL.txt", sep = "\t", header = TRUE)
tree <-read.tree("./Data/tree176.nwk")
rownames(data) <- data$Names

#removing charcolumns,convert to factors and log and standartize

data$Order <- as.factor(data$Order)
data$Family <- as.factor(data$Family)
data$Origin <- as.factor(data$Origin)
data$Status <- as.factor(data$Status)
data$DiurnalityN <- as.factor(data$DiurnalityN) 
data$Arboreality <- as.factor(data$Arboreality)
data$Shelter.safety <- as.factor(data$Shelter.safety)
data$Diet <- as.factor(data$Diet)
data$Group.living <- as.factor(data$Group.living)
data$Parental.care <- as.factor(data$Parental.care)
data$Mating.system <- as.factor(data$Mating.system)
data$Torpor <- as.factor(data$Torpor)
data$Play <- as.factor(data$Play)

data_mice <- data

data_mice$Names <- NULL
data_mice$Species <- NULL
data_mice$Order <- NULL
data_mice$Family <- NULL
data_mice$Common.Name <- NULL
data_mice$Status..Endangered..Vulnerable..Common..Abundant..Rare..or.sparse...Declining..Limited. <- NULL
data_mice$Dimorphism <- NULL
data_mice$ased <- NULL
data_mice$BodyM <- NULL
data_mice$BodyF <- NULL


#log and stdz


data_mice$BodyN <- log(data_mice$BodyN)
data_mice$Brain <- log(data_mice$Brain)
data_mice$Weaning.age <- log(data_mice$Weaning.age)
data_mice$Litter.size <- log (data_mice$Litter.size)
data_mice$HR <- log(data_mice$HR)
data_mice$Population.density <- log(data_mice$Population.density)
data_mice$FMR.Riek <- log (data_mice$FMR.Riek)

stdize = stdize = function(x, ...) {(x - min(x, ...)) / (max(x, ...) - min(x, ...))}


data_mice$Brain <- stdize(data_mice$Brain, na.rm = T)
data_mice$BodyN <- stdize(data_mice$BodyN, na.rm = T)
data_mice$Weaning.age <- stdize(data_mice$Weaning.age, na.rm = T)
data_mice$Litter.size <- stdize(data_mice$Litter.size, na.rm = T)
data_mice$HR <- stdize(data_mice$HR, na.rm = T)
data_mice$Population.density <- stdize(data_mice$Population.density, na.rm = T)
data_mice$FMR.Riek <- stdize(data_mice$FMR.Riek, na.rm = T)


library(VIM)

pdf(file="missing.pdf",width=9,height=12)
aggr_plot <- aggr(data_mice, col=c('navyblue','red'), numbers=TRUE, sortVars=TRUE, labels=names(data_mice), cex.axis=.5, gap=4, ylab=c("Histogram of missing data","Pattern"))

aggr_plot


dev.off()

a <- data[rowSums(is.na(data))<(length(data)-2),] #remove >3 NAs

```


#Phyomice
```{r setup, include=FALSE}

prec <- precomputePsi(tree)

imp <- mice(data_mice, m=5, meth = c("phpmm", "phpmm", "", "", "phpmm", "phpmm", "phpmm", "phpmm", "phpmm", "phpmm", "phpmm", "phpmm", "phpmm","phpmm","phpmm","phpmm", "phpmm", "phpmm"), psi = prec$psi, psiinv = prec$psiinv, maxit = 2)

pred <- imp$predictorMatrix 
pred[, "FMR.Riek"] <- 0
pred[, "Torpor"] <- 0
pred[, "Play"] <- 0
pred[, "Population.density"] <- 0
pred[, "HR"] <- 0



imp <- mice(data_mice, m=5, pred = pred, meth = c("phpmm", "phpmm", "", "", "phpmm", "phpmm", "phpmm", "phpmm", "phpmm", "phpmm", "phpmm", "phpmm", "phpmm","phpmm","phpmm","phpmm", "phpmm", "phpmm"), psi = prec$psi, psiinv = prec$psiinv, maxit = 2000)

save(imp, file = "imp2000.RData")


plot(imp)
stripplot(imp, pch = 20, cex = 1.2)

complete(imp, 2)

load("./Data/imp20000.Rdata")
```

GO BACK TO MCMC



#Non phylo imputation
```{r setup, include=FALSE}


md.pattern(data_mice)

imp <- mice(data_mice, m=1, seed = 23109, maxit = 20000)
print(imp)
plot(imp)

imp$imp$Diet
complete(imp)

stripplot(imp, pch = 20, cex = 1.2)

-
data1 <- complete(imp, 1)
data2 <- complete(imp, 2)
data3 <- complete(imp, 3)
data4 <- complete(imp, 4)
data5 <- complete(imp, 5)

```
